// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQvgmgwQhLAbKBAxDTJ8Cp-nb-yrkMlc',
    appId: '1:992859131837:web:e2a1ebfa8cc32df6414cd4',
    messagingSenderId: '992859131837',
    projectId: 'prsnlfinal',
    authDomain: 'prsnlfinal.firebaseapp.com',
    storageBucket: 'prsnlfinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDxDZZbLbPn84mhGPBhB7SirVo-vj2us',
    appId: '1:992859131837:android:47947969a5831052414cd4',
    messagingSenderId: '992859131837',
    projectId: 'prsnlfinal',
    storageBucket: 'prsnlfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxV9IxKpX4uMur3JfYjrE_8BgpD4z_Gc',
    appId: '1:992859131837:ios:9de238c49963dbb7414cd4',
    messagingSenderId: '992859131837',
    projectId: 'prsnlfinal',
    storageBucket: 'prsnlfinal.firebasestorage.app',
    iosBundleId: 'com.example.prsnlFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxV9IxKpX4uMur3JfYjrE_8BgpD4z_Gc',
    appId: '1:992859131837:ios:9de238c49963dbb7414cd4',
    messagingSenderId: '992859131837',
    projectId: 'prsnlfinal',
    storageBucket: 'prsnlfinal.firebasestorage.app',
    iosBundleId: 'com.example.prsnlFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlQvgmgwQhLAbKBAxDTJ8Cp-nb-yrkMlc',
    appId: '1:992859131837:web:0468336d3f3abeab414cd4',
    messagingSenderId: '992859131837',
    projectId: 'prsnlfinal',
    authDomain: 'prsnlfinal.firebaseapp.com',
    storageBucket: 'prsnlfinal.firebasestorage.app',
  );

}